version: "2"
services:
  db:
    image: mysql:5.7
    env_file: mysql.env
  redis:
    image: redis:4-alpine
  app:
    build: .
    env_file: ushahidi.env
    command: start
    ports:
      - "127.0.0.1:7080:8080"
    volumes:
      - storage-app-public:/var/www/storage/app/public
  platform_tasks:
    build: .
    env_file: ushahidi.env
    command: start
    volumes:
      - storage-app-public:/var/www/storage/app/public

volumes:
  # share storage/app/public between platform containers
  storage-app-public:
